In [1]:
import optuna
import numpy as np
# Turn off optuna logging
optuna.logging.set_verbosity(optuna.logging.WARNING)
# Self-defined modules
from config import *

# Estimate how much profit we can make if we buy stocks.

In [2]:
# Our budget including 1) The monthly house loan and 2) The monthly bill on house maintenance.
house_loan_monthly = 54166
bill_history = np.loadtxt('./bills.txt')
# Print for debug
print(bill_history[:10])
maintenance_history = bill_history[:,1]
tax_history = bill_history[:,2]
house_rent_history = bill_history[:,3]

[[12320.  3306.  9015. 30050.]
 [12341.  3311.  9030. 30100.]
 [12362.  3317.  9045. 30150.]
 [12382.  3322.  9060. 30201.]
 [12403.  3328.  9075. 30251.]
 [12424.  3333.  9090. 30301.]
 [12444.  3339.  9106. 30352.]
 [12465.  3344.  9121. 30402.]
 [12486.  3350.  9136. 30453.]
 [12507.  3355.  9151. 30504.]]


In [28]:
def advance():
    ans = cash
    net_worth_history = np.zeros((num_month, 2))
    for i in range(num_month):
        increment = house_loan_monthly + maintenance_history[i] + tax_history[i] - house_rent_history[i]
        ans += increment
        #tmp_ans = ans
        ans *= (1 + stock_inflation/12)
        #print("Before: ", tmp_ans, "After: ", ans)
        net_worth_history[i, 0] = ans
        net_worth_history[i, 1] = increment
    np.savetxt('./stock_net_worth.txt', net_worth_history, fmt='%d', header='Net worth of stock investment, increment', delimiter='\t')
    return ans

In [29]:
print("Cash: ", cash)
total_cost = np.sum(house_rent_history) + house_loan_monthly * num_month + cash
print("Total cost: ", total_cost)
total_investment = house_loan_monthly * num_month + cash - np.sum(house_rent_history - maintenance_history - tax_history)
print("Total investment: ", total_investment)
net_worth = advance()
print("Net worth: ", net_worth)

Cash:  3600000.0
Total cost:  37906159.0
Total investment:  14363979.0
Net worth:  53905713.28519675
